
# docker compose -f docker-compose.dev.yml up

name: crux-dev
services:
  db:
    image: postgres:17.4
    container_name: crux-dev-db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - crux_postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U crux -d cruxdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: crux-dev-pgadmin
    env_file:
      - ./pgadmin.env
    ports:
      - "5051:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - crux_pgadmin_dev_data:/var/lib/pgadmin

volumes:
  crux_postgres_dev_data:
  crux_pgadmin_dev_data: