name: crux

services:
  db:
    image: postgres:17.4
    container_name: crux-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - crux_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U crux -d cruxdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - proxy-net

  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crux-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:4001/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - proxy-net

  frontend:
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://crux-backend:4001
    env_file:
      - ./frontend/.env
    container_name: crux-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - proxy-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: crux-pgadmin
    restart: unless-stopped
    env_file:
      - ./pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - crux_pgadmin_data:/var/lib/pgadmin
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true

volumes:
  crux_postgres_data:
  crux_pgadmin_data:
